language: java

install:
 - wget https://github.com/nichiyoubi/line_tracer/releases/download/0.0.1-SNAPSHOT/linetracer-0.0.1-SNAPSHOT.jar
 - mvn install:install-file -Dfile=linetracer-0.0.1-SNAPSHOT.jar -DgroupId=jp.topse -DartifactId=line_tracer -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar

script:
 - mvn compile

